// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vTsuUyJBsoqwPKwGjvgKMg
// Component: lhTIjsw79-V
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: GrOEPhscx_v/component
import ProductCarousel from "../../ProductCarousel" // plasmic-import: DmNqlp5KZVpM/component
import ProductCard from "../../ProductCard" // plasmic-import: sFGOecZNEAdK/component
import Ratings from "../../Ratings" // plasmic-import: 4Cz3IJb9HjUp/component
import FeatureItem from "../../FeatureItem" // plasmic-import: KZlUJU-cQUJ/component
import BlogPost from "../../BlogPost" // plasmic-import: ZOltP1jkppDh/component
import Footer from "../../Footer" // plasmic-import: 2DtlwyDDA4m/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: LLj2xHLSZywX/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: vTsuUyJBsoqwPKwGjvgKMg/projectcss
import * as sty from "./PlasmicHome.module.css" // plasmic-import: lhTIjsw79-V/css
import arrivals1ZtlHWkKtDZiI from "./images/arrivals1.png" // plasmic-import: ztlHWkKtDZiI/picture
import arrivals2SQwl3GaZfoXc from "./images/arrivals2.png" // plasmic-import: sQWL3GAZfoXC/picture
import arrivals38XHq5HiNsaFj from "./images/arrivals3.png" // plasmic-import: 8xHq5HINsaFJ/picture
import arrivals4UmUnsJcHQxIh from "./images/arrivals4.png" // plasmic-import: UMUnsJcHQxIH/picture
import arrivals5PRK1WDvP0Y2 from "./images/arrivals5.png" // plasmic-import: P_rK1wDvP0y2/picture
import arrivals6CBkPLoRrtlX from "./images/arrivals6.png" // plasmic-import: CBk_pLORrtlX/picture
import arrivals7EkAmm6WqqcJ from "./images/arrivals7.png" // plasmic-import: ekAMM6wqqcJ_/picture
import arrivals8NFsa0QGp6Xkq from "./images/arrivals8.png" // plasmic-import: nFSA0QGp6Xkq/picture
import f2JsXrw2Ye6GL2 from "./images/f2.jpeg" // plasmic-import: jsXrw2YE6gL2/picture
import f3PeqJvaIj03EC from "./images/f3.jpeg" // plasmic-import: PeqJVAIj03eC/picture
import f4V7Dw0PSkl4F0 from "./images/f4.jpeg" // plasmic-import: v7DW0pSKL4F0/picture
import b1F2XBVuVHc4Jy from "./images/b1.jpeg" // plasmic-import: f2xBVuVHc4JY/picture
import b2W1J2KpE36Cj from "./images/b2.jpeg" // plasmic-import: w1j2kp_e36cj/picture
import b3MrjqP8Q67APi from "./images/b3.jpeg" // plasmic-import: MrjqP8Q67APi/picture
import adidasAoZeQj5L8Wp3 from "./images/adidas.png" // plasmic-import: AoZeQJ5l8WP3/picture
import hmHjM9Dw3Ep0T from "./images/hm.png" // plasmic-import: Hj_M9dw3ep0t/picture
import kappaPs3KBjjPlwqU from "./images/kappa.png" // plasmic-import: ps3kBjjPlwqU/picture
import lacosteUPweZrs1As2U from "./images/lacoste.png" // plasmic-import: uPWEZrs1as2u/picture
import levis0L2EJJjggbJ from "./images/levis.png" // plasmic-import: 0L2E_JJjggbJ/picture

export const PlasmicHome__VariantProps = new Array()

export const PlasmicHome__ArgProps = new Array()

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__siXm
            )}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__hmRnt
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__bvOFl
                )}
              >
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__fjg5M
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__xldbw
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns__aQxuC
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__eLOk
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iDh2J
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dls5)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals1ZtlHWkKtDZiI,
                        fullWidth: 120,
                        fullHeight: 120,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zWMnE
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__gi7Wm
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___9I0K8
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hb75T)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals2SQwl3GaZfoXc,
                        fullWidth: 138,
                        fullHeight: 116,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__t8Rmt
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Single Armchair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__d3Pns
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pMcMf
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__eh0Zz)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals38XHq5HiNsaFj,
                        fullWidth: 135,
                        fullHeight: 116,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__mcem4
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Armchair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__ctVbo
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zr4Nw
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___9Vo0)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals4UmUnsJcHQxIh,
                        fullWidth: 100,
                        fullHeight: 130,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__m6PIn
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Stylish Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__svhKu
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gzwg
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__siK1D)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals5PRK1WDvP0Y2,
                        fullWidth: 105,
                        fullHeight: 127,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$120.00"}
                  title={"Modern Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__a07D
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nWnxf
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__aHxRh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals6CBkPLoRrtlX,
                        fullWidth: 176,
                        fullHeight: 123,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$140.00"}
                  title={"Mapple Wood Dinning Table"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__jgOr
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zbVag
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__l5KPm)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals7EkAmm6WqqcJ,
                        fullWidth: 160,
                        fullHeight: 120,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$90.00"}
                  title={"Arm Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__kjyoo
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___4IIkk
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___3KQfm)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals8NFsa0QGp6Xkq,
                        fullWidth: 191,
                        fullHeight: 101,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$140.00"}
                  title={
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__hMps2
                      )}
                    >
                      {"Wooden Bed"}
                    </div>
                  }
                />
              </div>
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__gPuGw
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__zfYxl
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns__gJuY
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column___8WiDm
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__j65F9
                  )}
                  price={
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__ulC0K
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__cfLoj
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text___2MFcS
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={"withReviews"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column___6IXmz
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tpDgg
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__o2I4Q)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f2JsXrw2Ye6GL2,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zJ3To
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={"withReviews"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column___7C4Oa
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rw6Ol
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nfF3I)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f3PeqJvaIj03EC,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__na8OS
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={"withReviews"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column___7Dey0
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yvPj1
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nbTr)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f4V7Dw0PSkl4F0,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__v5J9D
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={"withReviews"}
                />
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__p3Gtq
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__kZtxc
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns__fhEnZ
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__xmi6
                )}
              >
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__c4KC)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pye9E)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b1F2XBVuVHc4Jy,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__mlXcZ
                )}
              >
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__bowsk)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___339T)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b2W1J2KpE36Cj,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__sJjAc
                )}
              >
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__t9Gsg)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xwQmO)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b3MrjqP8Q67APi,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__c3Xny
              )}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__vjceR)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: adidasAoZeQj5L8Wp3,
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__miFI)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: hmHjM9Dw3Ep0T,
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ii9Ug)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: kappaPs3KBjjPlwqU,
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__njmh)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: lacosteUPweZrs1As2U,
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__rkHin)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: levis0L2EJJjggbJ,
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicHome"
  } else {
    func.displayName = `PlasmicHome.${nodeName}`
  }
  return func
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
  }
)

export default PlasmicHome
/* prettier-ignore-end */
