// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vTsuUyJBsoqwPKwGjvgKMg
// Component: 8FB9biapNPhM
import * as React from "react"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: vTsuUyJBsoqwPKwGjvgKMg/projectcss
import * as sty from "./PlasmicMenuButton.module.css" // plasmic-import: 8FB9biapNPhM/css
import BarsIcon from "./icons/PlasmicIcon__Bars" // plasmic-import: MokXhTdT0I9P/icon
import TimesIcon from "./icons/PlasmicIcon__Times" // plasmic-import: PSo3KhiBfqI4/icon

export const PlasmicMenuButton__VariantProps = new Array("expanded")

export const PlasmicMenuButton__ArgProps = new Array("href")

function PlasmicMenuButton__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        projectcss.button,
        projectcss.root_reset,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox, {
          [sty.freeBox__expanded]: hasVariant(variants, "expanded", "expanded"),
        })}
      >
        {(hasVariant(variants, "expanded", "expanded") ? true : true) ? (
          <BarsIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___9G5P6,
              {
                [sty.svg__expanded___9G5P6XBee8]: hasVariant(
                  variants,
                  "expanded",
                  "expanded"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "expanded", "expanded") ? true : true) ? (
          <TimesIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___9Zywk,
              {
                [sty.svg__expanded___9ZywKxBee8]: hasVariant(
                  variants,
                  "expanded",
                  "expanded"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
      </div>
    </button>
  )
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenuButton__ArgProps,
      internalVariantPropNames: PlasmicMenuButton__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicMenuButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuButton"
  } else {
    func.displayName = `PlasmicMenuButton.${nodeName}`
  }
  return func
}

export const PlasmicMenuButton = Object.assign(
  // Top-level PlasmicMenuButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicMenuButton
    internalVariantProps: PlasmicMenuButton__VariantProps,
    internalArgProps: PlasmicMenuButton__ArgProps,
  }
)

export default PlasmicMenuButton
/* prettier-ignore-end */
