// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vTsuUyJBsoqwPKwGjvgKMg
// Component: 4Cz3IJb9HjUp
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: vTsuUyJBsoqwPKwGjvgKMg/projectcss
import * as sty from "./PlasmicRatings.module.css" // plasmic-import: 4Cz3IJb9HjUp/css
import StarIcon from "./icons/PlasmicIcon__Star" // plasmic-import: 60sFp4AEwUha/icon

export const PlasmicRatings__VariantProps = new Array("stars")

export const PlasmicRatings__ArgProps = new Array("numReviews")

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
          [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
          [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
          [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
          [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
          [sty.root__stars_zero]: hasVariant(variants, "stars", "zero"),
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__eiaz,
              {
                [sty.svg__stars_five__eiazULYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_zero__eiazFul1D]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__vRwpR,
              {
                [sty.svg__stars_five__vRwpRuLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__vRwpRItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__vRwpRxtM8]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__vRwpRlKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__vRwpRj3HaW]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__vRwpRful1D]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__zb0SW,
              {
                [sty.svg__stars_five__zb0SWuLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__zb0SWItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__zb0SWxtM8]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__zb0SWlKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__zb0SWj3HaW]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__zb0SWful1D]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__vMj5,
              {
                [sty.svg__stars_five__vMj5ULYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__vMj5ItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__vMj5XtM8]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__vMj5LKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__vMj5J3HaW]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__vMj5Ful1D]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__fOdIo,
              {
                [sty.svg__stars_five__fOdIOuLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__fOdIoItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__fOdIoxtM8]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__fOdIolKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__fOdIoj3HaW]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__fOdIOful1D]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__arJa8,
              {
                [sty.svg__stars_five__arJa8ULYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__arJa8ItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__arJa8XtM8]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__arJa8LKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__arJa8J3HaW]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__arJa8Ful1D]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__zonXk,
              {
                [sty.svg__stars_five__zonXkuLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__zonXkItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_three__zonXkLKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__zonXkJ3HaW]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___3AXsf,
              {
                [sty.svg__stars_five___3AXsFuLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four___3AXsfItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_three___3AXsflKrRz]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___4Lcrj,
              {
                [sty.svg__stars_five___4LcrjuLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four___4LcrjItmFc]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__fsld,
              {
                [sty.svg__stars_five__fslduLYm0]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews),
      })}
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings"
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`
  }
  return func
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps,
  }
)

export default PlasmicRatings
/* prettier-ignore-end */
